# Generated by Django 3.1.4 on 2020-12-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_age_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='malzemeler',
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'Yok'), ('Age', 'Yaş')], default='None', max_length=10),
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.age')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
            options={
                'verbose_name': 'Çeşitler',
                'verbose_name_plural': 'Çeşitler',
            },
        ),
    ]
