# Generated by Django 3.1.4 on 2020-12-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201203_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.CharField(default=0, max_length=200, verbose_name='Hasat Zamanı'),
            preserve_default=False,
        ),
    ]
