# Generated by Django 3.1.4 on 2020-12-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad&Soyad')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('email', models.CharField(max_length=30, verbose_name='E-Posta')),
                ('status', models.CharField(choices=[('Yeni', 'Yeni'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Tamamlandı', 'Tamamlandı')], default='Yeni', max_length=30)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
            },
        ),
    ]
