# Generated by Django 3.1.4 on 2020-12-02 18:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactformmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, verbose_name='Başlık')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Cevap')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'SSS',
                'verbose_name_plural': 'SSS',
            },
        ),
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Hakkımızda'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='whatsapp',
            field=models.CharField(max_length=100),
        ),
    ]
