# Generated by Django 3.1.4 on 2020-12-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_settinggallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settinggallery',
            options={'verbose_name': 'Galeri', 'verbose_name_plural': 'Galeri'},
        ),
    ]
